config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  post 'search', to: 'search#index'
  resources :products
  resources :payments
  resources :types
  resources :categories
  resources :user
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'home/index'
  root to: 'home#index'
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orderables
  has_many :products, through: :orderables
  has_many :payments

  def total
    orderables.to_a.sum(&:total)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_orderable = @cart.orderables.find_by(product_id: @product.id)
    if current_orderable && quantity > 0
      current_orderable.update(quantity:)
    elsif quantity <= 0
      current_orderable.destroy
    else
      @cart.orderables.create(product: @product, quantity:)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [turbo_stream.replace('cart',
                                                   partial: 'cart/cart',
                                                   locals: { cart: @cart }),
                              turbo_stream.replace(@product)]
      end
    end
  end

  def remove
    @line_item = Orderable.find_by(id: params[:product_id])
    @line_item.destroy
    redirect_to cart_path
  end
end

app/views/cart/_cart.html.erb
<%= turbo_frame_tag "cart" do %>
  <% if @cart.orderables.count > 0 %>
    <%= render "cart/orderables" %>
  <% else %>
    <p>Your cart is empty</p>
  <% end %>
<% end %>

app/views/cart/_orderables.html.erb
 <section class="row d-flex flex-row-reverse h-100" style="margin-top:-80px;"  >
 <div class="col-3 col-md-3" style="margin-right:30px;">
        <div class="card bg-success text-white rounded-3 mt-5">
          <div class="card-body">
            <div class="d-flex justify-content-between align-items-center mb-4">
              <h5 class="mb-0">Информация о товарах</h5>
            </div>
            <hr class="my-4">
            <div class="d-flex justify-content-between mb-4">
              <p class="mb-2">Сумма</p>
              <p class="mb-2"><%= @cart.total.round(2) %> BYN</p>
               <%= link_to "Оформить заказ", new_payment_path, class: 'btn btn-outline-light', style: "margin-top:-6px;"%>
          </div>
</section>
<section class="h-100" style="background-color: #eee; margin-top:-273px; ">
  <% @cart.orderables.order('id DESC').each do |orderable| %>
    <% product = orderable.product %>
      <div id="<%= "cart-#{product.id}" %>">
      <div class="container h-100 py-2" style="margin-top:-20px; margin-left:150px;" >
        <div class="row d-flex justify-content-left align-items-left h-100" >
          <div class="col-10" >
            <div class="d-flex justify-content-between align-items-center mb-4" >
          <div>
        </div>
        <%= form_with(url: cart_add_path) do |f| %>
         <div class=" mb-3" style="border:2px solid #d6d4d4; border-radius:35px; background-color:white;" >
          <div class="card-body p-4" >
            <div class="row d-flex justify-content-between align-items-center" >
              <div class="col-md-2 col-lg-2 col-xl-2" >
                  <% if product.image.attached?%>
                  <%= image_tag(product.image, class: "img-fluid", style: "border-radius:35px;") %>
                  <% end%>
              </div>
              <div class="col-md-3 col-lg-3 col-xl-3">
                <p class="lead fw-normal mb-2"><strong><%= product.name %></strong></p>
              </div>
                <%= f.hidden_field :id, value: product.id %>
              <div class="col-md-3 col-lg-3 col-xl-3 d-flex">
                <button class="btn btn-success px-1 me-2" 
                onclick="this.parentNode.querySelector('input[type=number]').stepDown()">
                -
                <i class="fas fa-minus"></i>
              </button>
                <%= f.number_field :quantity, value: orderable.quantity.to_i, min: 1, class:"form-control form-control-sm" %>
                  <button class="btn btn-success px-1 me-2"
                        onclick="this.parentNode.querySelector('input[type=number]').stepUp()">
                       +
                      </button>  
                </div>
              <div class="col-md-3 col-lg-2 col-xl-2 offset-lg-1">
                <h5 class="mb-0"><%= product.price %><strong> BYN</strong></h5>
                <br>
                <h5 class="mb-0"><strong>Сумма:<br></strong><%= orderable.total.round(2) %><strong> BYN</strong></h5>
              </div>
                    <% end %>
              <div class="col-md-1 col-lg-1 col-xl-1 text-end">
                <%= form_with(url: cart_remove_path) do |f| %>
                <%= f.hidden_field :product_id, value: orderable.id %>
                <%= f.submit "🗑️", class: "btn btn-danger"%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
       </div>
      </div>
    </div>
  </div>
  <% end %>
</section>

app/views/cart/show.html.erb
<%= turbo_frame_tag "cart" do %>
  <% if @cart.orderables.count > 0 %>
    <%= render "cart/orderables" %>
  <% else %>
    <h1 class="mt-5 mb-5 text-center">Ваша корзина пуста.<br> <b>Добавьте товар  </b><b>!</b></h1>
    <div class="col-md-12 text-center">
      <%= link_to 'Перейти в каталог', products_path, class: 'btn btn-danger btn-lg', style: "padding:15px 110px;" %>
    </div>
  <% end %>
<% end %>