config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  post 'search', to: 'search#index'
  resources :products
  resources :payments
  resources :types
  resources :categories
  resources :user
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'home/index'
  root to: 'home#index'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :type
  has_many :orderables, dependent: :destroy
  has_many :carts, through: :orderables

  has_one_attached :image

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 3 }

  def self.ransackable_attributes(auth_object = nil)
    ["composition", "created_at", "id", "manufacturer", "name", "price", "type_id", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["carts", "image_attachment", "image_blob", "orderables", "type"]
  end

  def set_name
    self[:name] = "#{Type.find(self[:type_id]).name} #{self[:name]}"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
    if params[:type_filter]
      @products = Product.where(type: Type.where(name: params[:type_filter]))
    elsif params[:category_filter]
      @products = Product.where(type: Type.where(category: Category.where(name: params[:category_filter])))
    end
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def search
    q = params[:product][:name]
    @products = Product.find(:all, :conditions => ["name LIKE %?%",q])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :composition, :price, :manufacturer, :type_id, :image, :search, :mass, :country, :recommendation)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label "Название", style: "display: block" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label "Описание", style: "display: block" %>
    <%= form.text_field :composition, class: 'form-control'%>
  </div>

  <div class="form-group mb-3">
    <%= form.label "Цена (BYN)", style: "display: block" %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label "Производитель: (ЧП Дарида)", style: "display: block" %>
    <%= form.text_field :manufacturer, class: 'form-control' %>
  </div>

   <div class="form-group mb-3">
    <%= form.label "Масса продукта: (100Г, 10Л, 5КГ)", style: "display: block" %>
    <%= form.text_field :mass, class: 'form-control' %>
  </div>

   <div class="form-group mb-3">
    <%= form.label "Страна производитель: (Беларусь)", style: "display: block" %>
    <%= form.text_field :country, class: 'form-control' %>
  </div>

    <div class="form-group mb-3">
    <%= form.label "Рекомендация:", style: "display: block" %>
    <%= form.text_field :recommendation, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group mb-3">
    <%= form.label "Подкатегория", style: "display: block" %>
    <%= form.collection_select :type_id, Type.order(:name), :id, :name, { prompt: 'Выберите тип товара' }, { class: 'form-control' } %>
  </div>

  <div class="actions mt-3 mb-3">
    <%= form.submit 'Готово', class: 'btn btn-success' %>
    <%= link_to 'Все продукты', products_path, class: 'btn btn-outline-dark' %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Название:</strong>
    <%= product.name %>
  </p>

  <p>
  <% if product.image.attached?%>
    <%= image_tag(product.image, style:"width: 200px;") %>
    <% end%>
  </p>

 <p>
    <strong>Описание:</strong>
    <%= product.composition %>
  </p>

  <p>
    <strong>Цена:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Производитель:</strong>
    <%= product.manufacturer %>
  </p>

  <p>
    <strong>Подкатегория:</strong>
    <%= product.type_id %>
  </p>

  

</div>

app/views/products/edit.html.erb
<div class="container mt-3 px-2">
<h1 class="text-center mt-3">Редактирование товара: </h1>
<div class="d-flex justify-content-center">
<%= render "form", product: @product %>

<br>
 <% if @product.image.attached?%>
    <%= image_tag(@product.image, style:"width: 300px;height: 400px; d-flex justify-content-center; margin:20px; border-radius:25px;", class: "img-fluid") %>
    <% end%>
<div>
</div>
</div>
<div>
</div>
<hr>

app/views/products/index.html.erb
<div class="container mt-1 px-1">
<%= search_form_for @q do |f| %>
 <nav id="navbar" class="navbarg">
        <ul>
          <li> <%= f.search_field :name_cont, class: 'form-control form-control-dark', placeholder: "Поиск..", style: 'border-radius: 15px; border: 2px solid grey; width:100%;'%></li>
          <li><%= f.submit "Поиск", class: 'btn btn-outline-danger' %></li>
          <li><%= sort_link(@q, :price, "Сортировка по цене: ", default_order: :asc, class: "nav-link px-2 text-secondary") %></li>
          <li><%= sort_link(@q, :name, "Сортировка по названию: ", default_order: :asc, class: "nav-link px-2 text-secondary") %></li>
      </nav><!-- .navbar -->
 

      
        
        <% end %>
<h1>Наши товары:</h1>
<% if current_user&.admin?%>
<h1><%= link_to 'Добавить товар', new_product_path, class: 'btn btn-outline-dark', style: "padding:10px 75px;"%></h1>
<%end%>
<div id="products">
  <% @products.each do |product| %>
  <div class="row row-cols-1 row-cols-md-3 g-3">
  <div class="col">
    <div class="card" style="border-radius: 15px;">
      <% if product.image.attached?%>
    <%= image_tag(product.image, style:"width: 450px; height: 500px; border-radius: 20px;", class: "img-fluid") %>
    <% end%>
      <div class="card-body">
        <div class="d-flex justify-content-center">
        <h5><%= link_to product.name, product, class: "text-dark" %></h5>
        </div>
          <div class="card-body pb-0">
            <div class="d-flex justify-content-center">
              <p style="font-size:20px;"><strong>Цена: </strong><%= product.price %> <strong>BYN</strong></p>
            </div>
          </div>
          <div class="card-body">
            <div class="d-flex justify-content-center align-items-center pb-0 mb-1">
               <% if current_user %>
              <%= form_with(url: cart_add_path) do |f| %>
                <%= f.hidden_field :id, value: product.id %>
                <div class="row g-0">
                  <div class="col-sm-6 col-md-8">
                    <div class="d-flex mb-4" style="max-width: 250px">
                      <button class="btn btn-danger px-3 me-2"
                        onclick="this.parentNode.querySelector('input[type=number]').stepDown(); return false;">
                        -
                      </button>

                      <div class="form-outline">
                        <%= f.number_field :quantity, value: 1, min: 1, class: 'form-control' %>
                      </div>

                      <button class="btn btn-danger px-3 ms-2"
                        onclick="this.parentNode.querySelector('input[type=number]').stepUp(); return false;">
                        +
                      </button>
                    </div>
                  </div>
                  <div class="col-6 col-md-4">
                    <%= f.submit 'В корзину', class: 'btn btn-outline-danger', style: 'margin-left:10px;'%>
                  </div>
                </div>
              <% end %>
            <% end %>
            </div>
          </div>
      </div>
    </div><br><br>
  </div

  
  <% end %>
 

app/views/products/new.html.erb
<div class="container mt-3 px-2">
<h1 class="text-center mt-3">Новый продукт</h1>
<div class="d-flex justify-content-center">
<%= render "form", product: @product %>

<br>
</div>
<div>
</div>
</div>
<hr>

app/views/products/show.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

<div class="container">
    <div class="card" style="margin-top:20px; border-radius:25px;">
        <div class="card-body">
            <h3 class="card-title"><%= @product.name %></h3>
            <div class="row">
                <div class="col-lg-5 col-md-5 col-sm-6">
                    <div class="white-box text-center"> 
                     <% if @product.image.attached?%>
                    <%= image_tag(@product.image, style:"width: 500px; border-radius: 15px;") %>
                    <%end%>
                    </div>
                </div>
                <div class="col-lg-7 col-md-7 col-sm-6">
                    <h4 class="box-title mt-5">Состав: </h4>
                    <p><%= @product.composition %></p>
                    <h2 class="box-title mt-5">Цена:  <%= @product.price %><small class="text-success">BYN</small></h2>
                    <h2 class="box-title mt-5">Масса продукта: </h2>
                    <p> <%= @product.mass %></p>
                    <h2 class="box-title mt-5">Cтрана производитель: </h2>
                    <p><%= @product.country %></p>
                    <h3 class="box-title mt-5">Производитель: </h3>
                    <p><%= @product.manufacturer %></p>
                    <h3 class="box-title mt-5">Рекомендации: </h3>
                    <p><%= @product.recommendation %></p>
                      <% if current_user %>
                    <%= form_with(url: cart_add_path) do |f| %>
                    <%= f.hidden_field :id, value: @product.id %>
                    <div class="row g-0">
                        <div class="col-sm-6 col-md-8">
                        <div class="d-flex mb-4" style="max-width: 250px">
                            <button class="btn btn-success px-3 me-2"
                            onclick="this.parentNode.querySelector('input[type=number]').stepDown(); return false;">
                            -
                            </button>

                            <div class="form-outline">
                            <%= f.number_field :quantity, value: 1, min: 1, class: 'form-control' %>
                            </div>

                            <button class="btn btn-success px-3 ms-2"
                            onclick="this.parentNode.querySelector('input[type=number]').stepUp(); return false;">
                            +
                            </button>
                        </div>
                        </div>
                        <div class="col-6 col-md-4">
                        <%= f.submit 'В корзину', class: 'btn btn-outline-success' %>
                        </div>
                    </div>
                    <% end %>
                <% end %>
                    <%= link_to "Назад", products_path, class: 'btn btn-outline-dark'%><br><br>
                    <% if current_user&.admin? %>
                    <%= link_to "Изменить продукт", edit_product_path(@product), class: "btn btn-secondary" %> <br><br>
                     <%= button_to "Удалить", @product, method: :delete , class: "btn btn-danger"%><br><br>
                     <%end%>
                 
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<br><br><br><hr>