config/routes.rb
Rails.application.routes.draw do
  get 'cart', to: 'cart#show'
  post 'cart/add'
  post 'cart/remove'
  post 'search', to: 'search#index'
  resources :products
  resources :payments
  resources :types
  resources :categories
  resources :user
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'home/index'
  root to: 'home#index'
end

app/views/layouts/_header.html.erb
 <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">
     
      <a href="http://localhost:3000/" class="logo d-flex align-items-center me-auto me-lg-0" style="margin-left:55px;">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <h1>Новый Континент</h1>
      </a>

      <nav id="navbar" class="navbarg">
        <ul>
          <li><%= link_to 'Главная', root_path, class: "nav-link px-2 text-secondary"%></li>
          <li><%= link_to 'Товары', products_path, class: "nav-link px-2 text-secondary"%></li>
          <li><a href="#contact" class="nav-link px-2 text-secondary">Контакты</a></li>
          <li><a href="#about" class="nav-link px-2 text-secondary">О нас</a></li>
      </nav><!-- .navbar -->
      <% if current_user %>
       <% if current_user&.admin? %>
           
              <a class="nav-link dropdown-toggle  " href="#" id="navbarDarkDropdownMenuLink" style='color: red; padding:-10px; font-size: 16px; margin-top: 5 px;' role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Просмотр 
              </a>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                <%= link_to 'Товары', products_path, class: 'dropdown-item' %>
                <%= link_to 'Категории', categories_path, class: 'dropdown-item' %>
                <%= link_to 'Подкатегории', types_path, class: 'dropdown-item' %>
              </ul>
          
          <% end %>
            <a class="nav-link dropdown-toggle btn btn-danger" style="color: white; font-size: 16px; border-radius:15px;padding:10px 20px;" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false" >
              👶
            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
              
              <%= link_to 'Личный кабинет', user_path(current_user), class: 'dropdown-item'%>
              <%= link_to 'История заказов', payments_path, class: 'dropdown-item' %>
              <%= link_to "Выйти", destroy_user_session_path, 'data-turbo-method': :delete, class: 'dropdown-item'%>
              
            </ul>
             <%= link_to '👜'.html_safe, cart_path, class: 'nav-link', style: "font-size:25px;"%>
            <%= link_to "Выйти", destroy_user_session_path, 'data-turbo-method': :delete, class: "btn btn-warning", style: "margin-left:5px; border-radius:15px;padding:10px 20px;"%>
 <% end %>
        <div class="text-end">
        <% if current_user %>
        <% if current_user&.admin? %>
           
              <a class="nav-link dropdown-toggle  " href="#" id="navbarDarkDropdownMenuLink" style='color: red; padding:-10px; font-size: 16px; margin-top: -2px;' role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Добавить 
              </a>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                <%= link_to 'Товар', new_product_path, class: 'dropdown-item' %>
                <%= link_to 'Категория', new_category_path, class: 'dropdown-item' %>
                <%= link_to 'Подкатегория', new_type_path, class: 'dropdown-item' %>
              </ul>
          
          <% end %>
        <% else %>
          <%= link_to 'Войти', new_user_session_path, class: "btn-book-a-table", style: 'border-radius: 15px; padding:12px 20px 12px 20px;'%>
          <%= link_to 'Регистрация', new_user_registration_path, class: "btn-book-a-table", style: 'border-radius: 15px;padding:12px 20px 12px 20px;'%>
           <% end %>
        </div>
      </div>
    </div>
    </div>
  </header><!-- End Header -->
  <nav class="navbar navbar-expand-lg navbar-dark p-3" style="background-color:#a80531;">
  <div class="container" style="margin-top:100px; margin-bottom:10px;">
    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
      <ul class="navbar-nav nav-items">
        <li class="nav-item dropdown" id="myDropdown">
          <a class="nav-link dropdown-toggle ms-5 "  id="navbarDarkDropdownMenuLink" style='color: white; font-size: 16px;' href="#" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-align-justify"></i>Категории</a>
          <ul class="dropdown-menu " aria-labelledby="navbarDarkDropdownMenuLink" style="border-radius:8px;">
                <% Category.select do |category| %>
              <li class="nav-item dropdown"> 
                <a class="dropdown-item" href="#"><%= category.name %> &raquo;</a>
                <ul class="submenu dropdown-menu" aria-labelledby="navbarDarkDropdownMenuLink" style="border-radius:8px;">
                  <% Type.where(category_id: category.id).select do |type| %>
                    <%= link_to type.name, products_path(type_filter: type.name), class: 'dropdown-item' %>
                  <% end %>
                </ul>
              </li>
            <% end %>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to 'Товары', products_path, class: 'btn btn-outline-light me-2', style: 'color: white;', style: 'border-radius: 15px;'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Пицца', products_path(type_filter: 'Пицца'), class: 'btn btn-outline-light me-2', style: 'border-radius: 15px;' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Шаурма', products_path(type_filter: 'Шаурма'), class: 'btn btn-outline-light me-2', style: 'border-radius: 15px;' %>
        </li>
        <li class="link_navbar">
          <%= link_to 'Суши', products_path(category_filter: 'Суши'), class: 'btn btn-outline-light me-2', style: 'border-radius: 15px;' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Напитки', products_path(category_filter: 'Напитки'), class: 'btn btn-outline-light me-2' , style: 'border-radius: 15px;'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Торты', products_path(category_filter: 'Торты'), class: 'btn btn-outline-light me-2', style: 'border-radius: 15px;' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<script>
document.addEventListener("DOMContentLoaded", function(){
if (window.innerWidth < 992) {
  document.querySelectorAll('.navbar .dropdown').forEach(function(everydropdown){
    everydropdown.addEventListener('hidden.bs.dropdown', function () {
        this.querySelectorAll('.submenu').forEach(function(everysubmenu){
          everysubmenu.style.display = 'none';
        });
    })
  });

  document.querySelectorAll('.dropdown-menu a').forEach(function(element){
    element.addEventListener('click', function (e) {
        let nextEl = this.nextElementSibling;
        if(nextEl && nextEl.classList.contains('submenu')) {	
          e.preventDefault();
          if(nextEl.style.display == 'block'){
            nextEl.style.display = 'none';
          } else {
            nextEl.style.display = 'block';
          }
        }
    });
  })
}
}); 
</script>

<style>
@media all and (min-width: 992px) {
	.dropdown-menu li{ position: relative; 	}
	.nav-item .submenu{ 
		display: none;
		position: absolute;
		left:100%; top:-7px;
	}
	.nav-item .submenu-left{ 
		right:100%; left:auto;
	}
	.dropdown-menu > li:hover{ background-color:  }
	.dropdown-menu > li:hover > .submenu{ display: block; }
}	

@media (max-width: 991px) {
  .dropdown-menu .dropdown-menu{
      margin-left:0.7rem; margin-right:0.7rem; margin-bottom: .5rem;
  }
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css' %>
    <%= javascript_importmap_tags %>
    

  <body class="d-flex flex-column min-vh-100" style="background-color:#f0ebeb">
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>